### ISSUE TITLE
Debug Menu Access

### ISSUE THREAD

**Issue by arb** [ShadowOne333/MaternalBound-Redux#10]
Is there a way to open the debug menu without GameGenie codes? I'm playing this mod on an Analogue Pocket which doesn't have GameGenie support as of this writing.

**Comment by arb** [comment]
Saw that someone asked about this on the Discord server [here](https://discord.com/channels/564985305384353793/817116623923576893/1096067152508878868). TL;DR, no. You can only access the debug menu via GameGenie.

**Comment by ShadowOne333** [comment]
It's possible to hard code it into the game.
All you need to do is to change the label in the ccscript file from the description of the ATM Card to the start of the Debug menu, but that requires you to compile the project.
