### ISSUE TITLE
(Bug) Can't Leave Lier X's house.

### ISSUE THREAD

**Issue by 12bones12** [ShadowOne333/MaternalBound-Redux#14]
Upon Onett opening you can enter Lier X's house to see the mani mani statue. Upon climbing up the ladder and entering the house area the trigger for the door is absent. You cannot leave the room.

**Comment by Anonymous941** [comment]
This is caused by patching the wrong type of ROM, see #5, #6 and #7

**Comment by ShadowOne333** [comment]
Yeah please make sure to patch using the BPS.
This was most likely caused by the wrong base ROM being patched.
Try another base ROM.
