### ISSUE TITLE
Visual glitches

### ISSUE THREAD

**Issue by ifighftdragons** [ShadowOne333/MaternalBound-Redux#4]
Visual glitching when walking upwards with the main character in EarthBound: MaternalBound Redux.
The back of the head of the character shows pixelated junk glitching out when walking upwards.

**Comment by ShadowOne333** [comment]
Do you have any pictures of it?

**Comment by ifighftdragons** [comment]
> Do you have any pictures of it? And when or where or does it happen?

Happens in the house at the beginning, only place I tested. Here is a video: https://www.veed.io/view/9efecb3a-1f58-4714-b006-ce1ef3a2186c/showcase?sharingWidget=true

**Comment by ShadowOne333** [comment]
Which patch did you use precisely?

**Comment by ifighftdragons** [comment]
Fixed the issue. I must have been patching it with the wrong patch, without expanding the ROM.
Works beautifully. Will update the review on RHDN as well. 

Thanks for the help!

**Comment by ShadowOne333** [comment]
Ah thank you for confirming it was an issue with the patching.
I patching in each patch individually when I got the notification from your response.

Glad you got it working!
