### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by chicofabri** [ShadowOne333/MaternalBound-Redux#5]
Can't get out of lier x agerate after him showing Ness the statue

**Comment by ShadowOne333** [comment]
Try to patch the game with a different base ROM, most likely issues like these are due to a wrong base ROM being used for patching, and/or a wrong patching process.

**Comment by brokenps2** [comment]
having the same issue, I don't think I used the wrong ROM, and I patched it correctly.

**Comment by ShadowOne333** [comment]
I'll rework the patch so that only the correct base ROM is asked for. I'll add a BPS or XDelta patch instead of a EBP so the patch itself asks for the right checksum. 

However, this would have to wait until the new year since I don't have much internet access atm

**Comment by ShadowOne333** [comment]
I have added both BPS and XDelta patches to the Downloads, and I got rid of the EBP one.
I still include an IPS file, but the preferred and recommended patch is specified to be the BPS.
With both BPS and XDelta I can ensure that the user will always provide the correct base ROM for the patching, or else the patch won't be applied.
