### ISSUE TITLE
Poo still say PSI Farewell

### ISSUE THREAD

**Issue by Yave-Yu** [ShadowOne333/MaternalBound-Redux#8]
After beat Giygas, the farewell scene, Poo still say PSI Farewell despite all PSI name were went back to PK xxx.

**Comment by ShadowOne333** [comment]
This is the intended behaviour.
PK is used for attacking moves in all Mother games, while PSI is used for defensive and non-attacking moves as well, so having Poo say PSI Farewell is intended to be a non-attacking psychic ability, hence the PSI and not PK.
